project:
  type: website

website:
  title: "Tesis — Ciclo Financiero Perú"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - text: Papers
        menu:
          - href: papers/camiz2020.qmd
            text: "Camiz et al. (2020)"
          - href: papers/camiz_et_al_2020.qmd
            text: "Camiz et al. (2020) v2"
          - href: papers/camiz_maulucci_roig_2010.qmd
            text: "Camiz, Maulucci & Roig (2010)"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
