<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.19">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Tuhin, Nobi, Rakib &amp; Lee (2025) — Long short-term memory autoencoder based network of financial indices – Tesis — Ciclo Financiero Perú</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-bf27225e3a48a9273f3daa8f8e829971.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-bb5ce4f09c3d713477d34b1921f208f7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Tesis — Ciclo Financiero Perú</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Inicio</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../marco_conceptual.html"> 
<span class="menu-text">Marco conceptual</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../marco_matematico_ae_lstm.html"> 
<span class="menu-text">Marco matemático AE/LSTM</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../linea_temporal.html"> 
<span class="menu-text">Línea temporal</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../glosario.html"> 
<span class="menu-text">Glosario</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../papers/diccionario_datos.html"> 
<span class="menu-text">Diccionario de datos</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-papers" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Papers</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-papers">    
        <li>
    <a class="dropdown-item" href="../papers/camiz_et_al_2020.html">
 <span class="dropdown-text">Camiz et al.&nbsp;(2020)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../papers/camiz_maulucci_roig_2010.html">
 <span class="dropdown-text">Camiz, Maulucci &amp; Roig (2010)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../papers/camiz_roig_2011.html">
 <span class="dropdown-text">Camiz &amp; Roig (2011)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../papers/camiz_cerda_atoche_2026.html">
 <span class="dropdown-text">Camiz, Cerda Hernández &amp; Atoche Murrieta (2026)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../papers/drehmann_borio_tsatsaronis_2012.html">
 <span class="dropdown-text">Drehmann, Borio &amp; Tsatsaronis (2012)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../papers/hochreiter_schmidhuber_1997.html">
 <span class="dropdown-text">Hochreiter &amp; Schmidhuber (1997)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../papers/hinton_salakhutdinov_2006.html">
 <span class="dropdown-text">Hinton &amp; Salakhutdinov (2006)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../papers/tuhin_et_al_2025.html">
 <span class="dropdown-text">Tuhin et al.&nbsp;(2025)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../papers/vincent_et_al_2008.html">
 <span class="dropdown-text">Vincent et al.&nbsp;(2008)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../papers/srivastava_mansimov_salakhutdinov_2015.html">
 <span class="dropdown-text">Srivastava, Mansimov &amp; Salakhutdinov (2015)</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Fichas preliminares</li>
        <li>
    <a class="dropdown-item" href="../papers/baldi_hornik_1989.html">
 <span class="dropdown-text">Baldi &amp; Hornik (1989)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../papers/bourlard_kamp_1988.html">
 <span class="dropdown-text">Bourlard &amp; Kamp (1988)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../papers/gers_schmidhuber_cummins_2000.html">
 <span class="dropdown-text">Gers, Schmidhuber &amp; Cummins (2000)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../papers/gal_ghahramani_2016.html">
 <span class="dropdown-text">Gal &amp; Ghahramani (2016)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../papers/fisher_1958.html">
 <span class="dropdown-text">Fisher (1958)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../papers/robert_escoufier_1976.html">
 <span class="dropdown-text">Robert &amp; Escoufier (1976)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../papers/plaut_2018.html">
 <span class="dropdown-text">Plaut (2018) — exploración</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="../papers/ciclo_economico.html">
 <span class="dropdown-text">Ciclo económico</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-data-bcrp" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Data BCRP</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-data-bcrp">    
        <li>
    <a class="dropdown-item" href="../notebooks/01_extraccion_bcrp.html">
 <span class="dropdown-text">01 · Extracción</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../notebooks/01b_extraccion_extendida_1985.html">
 <span class="dropdown-text">01b · Extracción extendida (desde 1985)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../notebooks/02_carga_y_verificacion.html">
 <span class="dropdown-text">02 · Carga y verificación</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../notebooks/03_analisis_exploratorio.html">
 <span class="dropdown-text">03 · Análisis exploratorio</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../notebooks/04_preprocesamiento.html">
 <span class="dropdown-text">04 · Preprocesamiento (trimestral)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../notebooks/04b_preprocesamiento_mensual.html">
 <span class="dropdown-text">04b · Preprocesamiento (mensual)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../notebooks/04c_preprocesamiento_extendido.html">
 <span class="dropdown-text">04c · Preprocesamiento extendido (1985+)</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-modelamiento" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Modelamiento</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-modelamiento">    
        <li>
    <a class="dropdown-item" href="../notebooks/05_pca.html">
 <span class="dropdown-text">05 · PCA (trimestral)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../notebooks/05b_pca_componentes_suavizadas.html">
 <span class="dropdown-text">05b · Componentes en el tiempo y suavizado (mensual)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../notebooks/06a_seleccion_ventana_epca.html">
 <span class="dropdown-text">06a · Selección de ventana (trimestral)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../notebooks/06b_seleccion_ventana_epca_mensual.html">
 <span class="dropdown-text">06b · Selección de ventana (mensual)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../notebooks/06_epca.html">
 <span class="dropdown-text">06 · EPCA (mensual)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../notebooks/07_verificacion_rcamiz.html">
 <span class="dropdown-text">07 · Verificación Rcamiz ↔︎ scikit-learn</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../notebooks/08_autoencoder.html">
 <span class="dropdown-text">08 · Autoencoders</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../notebooks/09_lstm_autoencoder.html">
 <span class="dropdown-text">09 · LSTM-Autoencoder y regímenes</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#datos-identificadores" id="toc-datos-identificadores" class="nav-link active" data-scroll-target="#datos-identificadores">1. Datos identificadores</a></li>
  <li><a href="#referencia-completa-apa-7.ª-edición" id="toc-referencia-completa-apa-7.ª-edición" class="nav-link" data-scroll-target="#referencia-completa-apa-7.ª-edición">2. Referencia completa (APA 7.ª edición)</a></li>
  <li><a href="#clasificación-temática" id="toc-clasificación-temática" class="nav-link" data-scroll-target="#clasificación-temática">3. Clasificación temática</a></li>
  <li><a href="#resumen-analítico" id="toc-resumen-analítico" class="nav-link" data-scroll-target="#resumen-analítico">4. Resumen analítico</a>
  <ul class="collapse">
  <li><a href="#problema-abordado" id="toc-problema-abordado" class="nav-link" data-scroll-target="#problema-abordado">Problema abordado</a></li>
  <li><a href="#propuesta-metodológica-arquitectura-y-procedimiento" id="toc-propuesta-metodológica-arquitectura-y-procedimiento" class="nav-link" data-scroll-target="#propuesta-metodológica-arquitectura-y-procedimiento">Propuesta metodológica (arquitectura y procedimiento)</a></li>
  </ul></li>
  <li><a href="#conceptos-clave-equivalencia-de-dominio" id="toc-conceptos-clave-equivalencia-de-dominio" class="nav-link" data-scroll-target="#conceptos-clave-equivalencia-de-dominio">5. Conceptos clave (equivalencia de dominio)</a></li>
  <li><a href="#aporte-a-la-tesis-limitaciones-y-diferenciación" id="toc-aporte-a-la-tesis-limitaciones-y-diferenciación" class="nav-link" data-scroll-target="#aporte-a-la-tesis-limitaciones-y-diferenciación">6. Aporte a la tesis, limitaciones y diferenciación</a>
  <ul class="collapse">
  <li><a href="#aporte-por-qué-este-paper-es-más-valioso-que-los-clásicos-de-19972006-para-tu-diferenciación" id="toc-aporte-por-qué-este-paper-es-más-valioso-que-los-clásicos-de-19972006-para-tu-diferenciación" class="nav-link" data-scroll-target="#aporte-por-qué-este-paper-es-más-valioso-que-los-clásicos-de-19972006-para-tu-diferenciación">Aporte — por qué este paper es más valioso que los clásicos de 1997/2006 para tu diferenciación</a></li>
  <li><a href="#limitaciones-reconocidas-por-los-propios-autores-y-relevantes-para-tu-adaptación" id="toc-limitaciones-reconocidas-por-los-propios-autores-y-relevantes-para-tu-adaptación" class="nav-link" data-scroll-target="#limitaciones-reconocidas-por-los-propios-autores-y-relevantes-para-tu-adaptación">Limitaciones (reconocidas por los propios autores, y relevantes para tu adaptación)</a></li>
  </ul></li>
  <li><a href="#referencias-internas-relevantes" id="toc-referencias-internas-relevantes" class="nav-link" data-scroll-target="#referencias-internas-relevantes">7. Referencias internas relevantes</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Tuhin, Nobi, Rakib &amp; Lee (2025) — Long short-term memory autoencoder based network of financial indices</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="datos-identificadores" class="level2">
<h2 class="anchored" data-anchor-id="datos-identificadores">1. Datos identificadores</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Campo</th>
<th>Detalle</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Código de ficha</strong></td>
<td>FB-006 <em>(verificar numeración contra fichas ya existentes en el repo)</em></td>
</tr>
<tr class="even">
<td><strong>Fecha de procesamiento</strong></td>
<td>29 de julio de 2026</td>
</tr>
<tr class="odd">
<td><strong>Procesado por</strong></td>
<td>Roberto Samaniego Salcedo</td>
</tr>
</tbody>
</table>
</section>
<section id="referencia-completa-apa-7.ª-edición" class="level2">
<h2 class="anchored" data-anchor-id="referencia-completa-apa-7.ª-edición">2. Referencia completa (APA 7.ª edición)</h2>
<p>Tuhin, K. H., Nobi, A., Rakib, M. H., &amp; Lee, J. W. (2025). Long short-term memory autoencoder based network of financial indices. <em>Humanities and Social Sciences Communications, 12</em>, Article 100. https://doi.org/10.1057/s41599-025-04412-y</p>
<blockquote class="blockquote">
<p><strong>Nota de verificación</strong>: la página muestra “…” tras el tercer autor listado (posibles autores adicionales no visibles en el extracto obtenido) — verificar la lista completa de autores contra la fuente original antes de citar formalmente.</p>
</blockquote>
</section>
<section id="clasificación-temática" class="level2">
<h2 class="anchored" data-anchor-id="clasificación-temática">3. Clasificación temática</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Campo</th>
<th>Detalle</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Área principal</strong></td>
<td>Redes financieras construidas mediante Autoencoder LSTM; detección de crisis financieras a través de propiedades topológicas de red</td>
</tr>
<tr class="even">
<td><strong>Área secundaria</strong></td>
<td>Comparación metodológica frente a métodos clásicos de construcción de redes (correlación de Pearson, información mutua, causalidad de Granger, transferencia de entropía)</td>
</tr>
<tr class="odd">
<td><strong>Relevancia para la tesis</strong></td>
<td><strong>ALTA — sostiene directamente tu diferenciación metodológica hacia Autoencoders/LSTM.</strong> A diferencia de Camiz et al., este paper no usa PCA/HFC/EPCA en absoluto: es un antecedente metodológico puro de deep learning aplicado a detección de regímenes/crisis financieras, con una técnica concreta y transferible (ver Sección 6).</td>
</tr>
<tr class="even">
<td><strong>Frente de la tesis al que aporta</strong></td>
<td>Frente 1 (Bibliografía), Frente 3 (Marco matemático — arquitectura Autoencoder y métricas de régimen)</td>
</tr>
</tbody>
</table>
</section>
<section id="resumen-analítico" class="level2">
<h2 class="anchored" data-anchor-id="resumen-analítico">4. Resumen analítico</h2>
<section id="problema-abordado" class="level3">
<h3 class="anchored" data-anchor-id="problema-abordado">Problema abordado</h3>
<p>Inferir la estructura de red (correlaciones direccionales) entre 375 acciones del S&amp;P 500 a partir únicamente de sus series de retornos diarios (2000–2022, 5786 días de cotización), y usar las propiedades topológicas de esa red para <strong>identificar crisis financieras</strong> (burbuja punto-com 2002, crisis financiera global 2008, crisis de deuda soberana europea 2011, caída global 2015, pandemia COVID-19 2020) sin necesidad de etiquetas ni modelos supervisados.</p>
</section>
<section id="propuesta-metodológica-arquitectura-y-procedimiento" class="level3">
<h3 class="anchored" data-anchor-id="propuesta-metodológica-arquitectura-y-procedimiento">Propuesta metodológica (arquitectura y procedimiento)</h3>
<ol type="1">
<li><strong>Preprocesamiento</strong>: retornos logarítmicos diarios normalizados por año (media y desviación estándar propias de cada año), segmentados en ventanas deslizantes de 5 días.</li>
<li><strong>Arquitectura LSTM Autoencoder de 5 capas</strong>: dos capas LSTM como codificador → <strong>una capa densa central (bottleneck)</strong> → dos capas LSTM como decodificador. La reconstrucción de cada acción usa como insumo las series de <em>todas las demás</em> acciones simultáneamente.</li>
<li><strong>Extracción de la matriz de “influencia”</strong>: tras entrenar el modelo de forma no supervisada (pérdida = error cuadrático medio de reconstrucción), <strong>la matriz de pesos de la capa densa central se interpreta como matriz de correlación/influencia entre series</strong> — asimétrica (direccional), a diferencia de una matriz de correlación clásica.</li>
<li><strong>Construcción de redes de umbral (threshold networks)</strong>: se fija un umbral (media + desviación estándar de los pesos absolutos) para retener solo conexiones significativas, generando una red por año.</li>
<li><strong>Métricas topológicas por año</strong>: coeficiente de clustering promedio, entropía estructural, longitud promedio de camino más corto, centralidad de alcance global (GRC), densidad de red, grado máximo (in/out-degree).</li>
<li><strong>Hallazgo central</strong>: durante los períodos de crisis, las redes muestran <strong>mayor clustering, menor entropía estructural (más jerárquicas, dominadas por pocos nodos), mayor densidad y mayor GRC</strong> — un patrón topológico distintivo y detectado consistentemente en las cinco crisis estudiadas, superando en claridad a los métodos clásicos de construcción de redes (Pearson, información mutua, Granger, transferencia de entropía).</li>
<li><strong>Análisis sectorial</strong>: mediante un “Índice de Direccionalidad” se identifica qué sectores dominan la influencia durante cada crisis (ej. Financials en 2008 y 2011; Tecnología de la Información y Salud en COVID-19 2020).</li>
</ol>
</section>
</section>
<section id="conceptos-clave-equivalencia-de-dominio" class="level2">
<h2 class="anchored" data-anchor-id="conceptos-clave-equivalencia-de-dominio">5. Conceptos clave (equivalencia de dominio)</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Concepto del paper (mercado bursátil EE.UU.)</th>
<th>Equivalente/adaptación para tu tesis (ciclo financiero peruano)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>375 series de retornos diarios de acciones S&amp;P 500</td>
<td>Tus ~15-17 series macrofinancieras mensuales/trimestrales del BCRP — <strong>nota importante de escala</strong>: aquí son 5786 observaciones diarias; tu dataset BCRP tiene ~263 observaciones mensuales — una diferencia de orden de magnitud relevante (ver limitaciones).</td>
</tr>
<tr class="even">
<td>Capa densa central del Autoencoder como matriz de “influencia” direccional</td>
<td>Podría adaptarse como una alternativa no lineal y direccional a la matriz de correlación usada en PCA/HFC — útil para contrastar con los grupos hallados por HFC en Camiz-Cerda-Atoche (2026).</td>
</tr>
<tr class="odd">
<td>Umbral dinámico/fijo sobre pesos para construir redes de umbral</td>
<td>Método candidato para definir de forma objetiva “conexiones relevantes” entre indicadores BCRP, análogo al criterio de corte de jerarquía en HFC (segundo autovalor &lt; 0.7).</td>
</tr>
<tr class="even">
<td>Métricas topológicas (clustering, entropía estructural, densidad, GRC) que suben/bajan en crisis</td>
<td><strong>Aporta directamente a tu diferenciación #3</strong> (detección explícita de regímenes): estas métricas, calculadas año a año (o ventana a ventana), podrían servir como tu propio indicador cuantitativo de “régimen de estrés financiero” para el caso peruano, validable contra episodios conocidos (crisis 2008, taper tantrum 2013, COVID 2020).</td>
</tr>
<tr class="odd">
<td>Entrenamiento del modelo por año (no por ventana móvil continua)</td>
<td>Diferente del EPCA de Camiz (ventana móvil continua). Es una alternativa metodológica a evaluar: ¿ventana móvil continua (estilo EPCA) o reentrenamiento por período fijo (estilo este paper)? Puede ser un punto de comparación explícito en tu tesis.</td>
</tr>
</tbody>
</table>
</section>
<section id="aporte-a-la-tesis-limitaciones-y-diferenciación" class="level2">
<h2 class="anchored" data-anchor-id="aporte-a-la-tesis-limitaciones-y-diferenciación">6. Aporte a la tesis, limitaciones y diferenciación</h2>
<section id="aporte-por-qué-este-paper-es-más-valioso-que-los-clásicos-de-19972006-para-tu-diferenciación" class="level3">
<h3 class="anchored" data-anchor-id="aporte-por-qué-este-paper-es-más-valioso-que-los-clásicos-de-19972006-para-tu-diferenciación">Aporte — por qué este paper es más valioso que los clásicos de 1997/2006 para tu diferenciación</h3>
<p>A diferencia de Hochreiter &amp; Schmidhuber (1997) o Hinton &amp; Salakhutdinov (2006), que son referencias teóricas fundacionales sin aplicación a ciclo/regímenes financieros, <strong>este paper (2025) es precedente metodológico directo y reciente</strong> de exactamente lo que propone tu Ficha de Inscripción: usar Autoencoders/LSTM para <strong>detectar regímenes/crisis financieras</strong>, no solo para pronosticar o comprimir datos. Te da:</p>
<ul>
<li>Una <strong>arquitectura concreta y replicable</strong> (5 capas: 2 LSTM encoder + densa central + 2 LSTM decoder) que puedes adaptar o citar como punto de partida para tu propio Autoencoder temporal.</li>
<li>Un <strong>procedimiento formal para convertir la salida del Autoencoder en un indicador de régimen</strong> (métricas topológicas de red basadas en la matriz de pesos), que es precisamente el tipo de “detección explícita de regímenes validada contra episodios históricos” que identificamos como tu diferenciación #3 frente a Camiz-Cerda-Atoche (2026).</li>
<li>Evidencia empírica de que este enfoque <strong>supera a métodos clásicos</strong> (correlación, información mutua, Granger, transferencia de entropía) en identificar crisis con claridad — argumento citable para justificar por qué vale la pena ir más allá de PCA/HFC/EPCA en tu propia tesis.</li>
</ul>
</section>
<section id="limitaciones-reconocidas-por-los-propios-autores-y-relevantes-para-tu-adaptación" class="level3">
<h3 class="anchored" data-anchor-id="limitaciones-reconocidas-por-los-propios-autores-y-relevantes-para-tu-adaptación">Limitaciones (reconocidas por los propios autores, y relevantes para tu adaptación)</h3>
<ul>
<li><strong>Requiere datasets grandes</strong>: los autores mismos señalan que el enfoque exige “cantidades sustanciales de datos” para entrenar efectivamente. Esto es una limitación <strong>crítica para tu adaptación</strong>: el paper usa 5786 observaciones diarias × 375 series; tu dataset BCRP tiene aproximadamente 263 observaciones mensuales × 15-17 series — una diferencia de escala de más de un orden de magnitud. Tendrás que evaluar cuidadosamente si un Autoencoder/LSTM es viable con tan pocas observaciones, posiblemente requiriendo arquitecturas mucho más simples (menos capas/unidades) o técnicas de regularización agresivas.</li>
<li>Computacionalmente más demandante que métodos clásicos.</li>
<li><strong>Interpretabilidad limitada</strong> (“caja negra”) — los propios autores lo reconocen como reto para la interpretación económica de los pesos aprendidos, algo que contrasta con la interpretabilidad explícita que ofrece HFC (ventaja que Camiz-Cerda-Atoche 2026 explota deliberadamente).</li>
<li>Aplicado a acciones bursátiles individuales, no a indicadores macrofinancieros agregados — la transferencia de dominio (de red de acciones a red de indicadores macro) requiere justificación propia.</li>
<li>Red direccional pero no simétrica — los autores mismos plantean como trabajo futuro generar pesos simétricos para poder aplicar MST/PMFG, técnicas que si podrían conectar más directamente con el enfoque de Camiz (HFC produce agrupamientos, no jerarquías de red en el sentido de teoría de grafos).</li>
</ul>
</section>
</section>
<section id="referencias-internas-relevantes" class="level2">
<h2 class="anchored" data-anchor-id="referencias-internas-relevantes">7. Referencias internas relevantes</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Referencia citada en el paper</th>
<th>Prioridad</th>
<th>Estado en el proyecto</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Hochreiter &amp; Schmidhuber (1997) — Long Short-Term Memory</td>
<td>Ya identificada como pendiente de fichar</td>
<td>Pendiente — referencia fundacional de LSTM, aún no fichada</td>
</tr>
<tr class="even">
<td>Sagheer &amp; Kotb (2019) — Unsupervised Pre-training of a Deep LSTM-based Stacked Autoencoder for Multivariate Time Series Forecasting</td>
<td>Alta — combina LSTM + Autoencoder + series multivariadas, muy cercano a tu propio diseño planeado</td>
<td>No identificado en tu carpeta; considerar localizar</td>
</tr>
<tr class="odd">
<td>Baiardi et al.&nbsp;(2020) — The Dynamics of the S&amp;P 500 under a Crisis Context: Insights from a Three-Regime Switching Model</td>
<td>Alta — modelo de cambio de régimen (3 regímenes) aplicado a mercado bursátil bajo crisis, directamente relacionado con tu concepto de “régimen”</td>
<td>No identificado en tu carpeta; considerar localizar</td>
</tr>
<tr class="even">
<td>Almog &amp; Shmueli (2019) — Structural entropy: monitoring correlation-based networks over time with application to financial markets</td>
<td>Media-alta — métrica de entropía estructural usada como indicador temprano de crisis, aplicable a tu detección de regímenes</td>
<td>No identificado en tu carpeta</td>
</tr>
<tr class="odd">
<td>Nobi &amp; Lee (2017) — Systemic risk and hierarchical transitions of financial networks</td>
<td>Media — antecedente de transiciones jerárquicas en redes financieras durante crisis</td>
<td>No identificado en tu carpeta</td>
</tr>
</tbody>
</table>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>